### ISSUE TITLE
Do I need to use cross-compiler to build this for STM32?

### ISSUE THREAD

**Issue by gevorgyana** [littlefs-project/littlefs#1039]
Do I need this? https://developer.arm.com/Tools%20and%20Software/GNU%20Toolchain

It seems that the Makefile in the sources can produce an archive, but then I need to link it together with the actual platform dependent code, correct?

**Comment by BenBE** [comment]
You need to build the code with the same compiler you also use to build the rest of your firmware for the STM32 …

**Comment by geky** [comment]
To be honest the default liblfs.a built by `make` exists just so `make` does something. It's useful for checking for compilation/linking errors, but most projects in this space integrate at the source code level using their own build system.
