### ISSUE TITLE
Lfs_file_sync is returning LFS_ERR_NOSPC with alot of memory left to it's disposal. 

### ISSUE THREAD

**Issue by Karlhead** [littlefs-project/littlefs#479]
Hello, 

I'm facing som issues which I'm having a hard time understanding. I've been using lfs for some time now without experiencing this issue before, but lately this issue has been surfacing more than once. 

I'm downloading data into several files, one at a time, around 10 files with approx. 80 KB data in each file. The first 9 files are succesfully filled with data and closed correctly, but when I'm trying to close the last file, I will get the LFS_ERR_NOSPC error code returned from the **lfs_file_close**-function, and the same thing happends if I try to call **lfs_file_sync** before **lfs_file_close** as well. The problem is consistent until I re-format the filesystem. 

As I'm debugging the **lfs_dir_commitattr**-function I can see that off + dsize is larger than end, resulting in the following return:
dsize = 16
commit->block = 7712
commit->off = 490
commit->begin = 0
commit->end = 504
if (commit->off + dsize > commit->end) {
        return LFS_ERR_NOSPC;
    }

However, there is no way that my device is out of memory. There is a total of 8388608 blocks (512B each) to lfs's disposal.
When calling lfs_fs_size, I can verify that only 1960 blocks are in use and 8386648 blocks are left.

Any help would be greatly appreciated.

**Comment by pedromarinho94** [comment]
@Karlhead Were you able to solve this? I'm having the same issue.
