### ISSUE TITLE
When open file with flag LFS_O_APPEND, lfs_file_write() will always set file pointer to the end of file.

### ISSUE THREAD

**Issue by shscp** [littlefs-project/littlefs#549]
Even if lfs_file_seek() is called before lfs_file_write() . This is not reasonable.

**Comment by geky** [comment]
Hi @shscp, this behavior is defined by POSIX:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/open.html

> ```
> O_APPEND
>    If set, the file offset shall be set to the end of the file prior to each write.
> ```

I can confirm this is how O_APPEND works on any other filesystem that follows POSIX.

---

If you need to change the location with seek, why are you opening the file with LFS_O_APPEND? You could instead use seek to go to the end of the file when needed:

```
lfs_file_seek(&lfs, &file, 0, LFS_SEEK_END)
```
