### ISSUE TITLE
Test suite will not run on macOS - test.py hangs before executing tests

### ISSUE THREAD

**Issue by pjdennis** [littlefs-project/littlefs#554]
Running 'make test' on Mac results in a hang with 100% CPU utilization after displaying '====== building ======'

This occurs because test.py expects pty.readline() to raise an OS error when the subprocess has exited, however this is not the case on MacOS (which returns empty string instead.) Some notes on this behavior can be found here: https://stackoverflow.com/a/42008071.

I can confirm that pull request #529 fixes this issue for me - all tests pass (817/817) after applying the changes to master on top of 1863dc7. I am using Python 3.9.4 on macOS 10.15.7.

**Comment by geky** [comment]
I'm assuming this is fixed in #529, which is on its way in. I'm going to go ahead and close this but feel free to reopen if it's still an issue. Thanks for creating an issue.
