### ISSUE TITLE
STM32H7 Boot_Count Updates w/ Errors

### ISSUE THREAD

**Issue by Artificial-Sparkz** [littlefs-project/littlefs#561]
I am testing the boot_count example code provided on the homepage. My QSPI chip is the MT25QL512ABB with 64MB of NOR Flash storage. I verified reading, writing, and erasing to the QSPI independently of the project. The two errors l receive are:

../Core/Src/lfs.c:1790:debug: Bad block at 0x0
../Core/Src/lfs.c:1795:warn: Superblock 0x0 has become unwritable

Weirdly the boot_count did update to 16 before the file system froze completely:

![bad](https://user-images.githubusercontent.com/84698378/119415875-b3fe0580-bcaf-11eb-9f4e-cb3bbd91e71d.png)

Parameters:

        uint8_t lfs_read_buf[4096];
        uint8_t lfs_prog_buf[4096];
        uint8_t lfs_lookahead_buf[512];

        // block device operations
	cfg.read  = block_device_read;
	cfg.prog  = block_device_prog;
	cfg.erase = block_device_erase;
	cfg.sync  = block_device_sync;`

	// block device configuration
	cfg.read_size = 256;
	cfg.prog_size = 256;
	cfg.block_size = 4096;
	cfg.block_count = 16384;
	cfg.lookahead_size = 4096;
	cfg.cache_size = 4096;
	cfg.block_cycles = 500;

	cfg.read_buffer = lfs_read_buf;
	cfg.prog_buffer = lfs_prog_buf;
	cfg.lookahead_buffer = lfs_lookahead_buf;`

**Interface:**

       int block_device_read(const struct lfs_config *c, lfs_block_t block,
	lfs_off_t off, void *buffer, lfs_size_t size)
        {
	BSP_QSPI_Read(0, (uint8_t*)buffer, (block * c->block_size + off), size);
	return 0;
        }

       int block_device_prog(const struct lfs_config *c, lfs_block_t block,
	lfs_off_t off, const void *buffer, lfs_size_t size)
        {
	BSP_QSPI_Write(0, (uint8_t*)buffer, (block * c->block_size + off), size);

	return 0;
        }

        int block_device_erase(const struct lfs_config *c, lfs_block_t block)
        {
	BSP_QSPI_EraseBlock(0, block * c->block_size, MT25TL01G_ERASE_4K);

	return 0;
         }

        int block_device_sync(const struct lfs_config *c)
        {
	return 0;
         }                 `
                           
I converted the interface code over from another example with a different QSPI chip. I would appreciate any advice you could give on these errors. Thank you.

**Comment by e107steved** [comment]
Does your interface use DMA? If so, have you fully taken account of memory caching?

**Comment by Artificial-Sparkz** [comment]
@e107steved Thank you for the help. 
I reduced the lfs cache parameter to cfg.cache_size = 2048,

This solved the issue.
