### ISSUE TITLE
Can't install silero

### ISSUE THREAD

**Issue by Michal-Dudcenko** [littlefs-project/littlefs#682]
>pip install silero
	Collecting silero
	  Using cached silero-0.1.0-py3-none-any.whl (24 kB)
	Requirement already satisfied: omegaconf>=2.1.0 in c:\users\asusd\appdata\local\programs\python\python310\lib\site-packages
	(from silero) (2.2.1)
	
	ERROR: Could not find a version that satisfies the requirement torchaudio==0.10.0 (from silero) (from versions: 0.11.0)
	ERROR: No matching dis
tribution found for torchaudio==0.10.0

![image](https://user-images.githubusercontent.com/87039655/169517042-167904c7-de71-4edf-96aa-0f9dc5cbeff9.png)

**Comment by geky** [comment]
Are you by any chance running pip in Windows on top of LittleFS? It would be very interesting to learn how you got that working and if it could be packaged as a reusable driver.

If not I think you have the wrong repo :)
