### ISSUE TITLE
Timing Problem

### ISSUE THREAD

**Issue by hackenpiep** [littlefs-project/littlefs#688]
Hey,
I am trying to use littlefs for my project. Unfortunately I have not made it yet. In the first step, I call mount_fs, which returns me an error -84 (is clear because the superblocks have not been found yet). When I call format_fs(), I get an error -28 and when I call mount_fs() again, I get -84 . Because I bought a j link debugger a year ago, I can debug the program. but when I debug the code line by line, I get no error on mount_fs(). So I suspect that there is a timing problem when reading, writing or deleting data. I use a spi flash with gpio. gpio always waits with an action until the previous action is finished, so it can't really be the writing, reading or deleting of data on my flash. If I don't debug each line individually the error occurs (as far as I can see) in these lines

`

     state = lfs_dir_splittingcompact(lfs, dir, attrs, attrcount, dir, 0, dir->count);

    if (state < 0) {

    return state;
    }

`

my config:

.read_size = 16,

.prog_size = 16,

.block_size = 4096,

.block_count = 128,

.cache_size = 32,

.lookahead_size = 32,

.block_cycles = 500,

my test code

`

       int err = lfs_mount(&lfs, &cfg_littlefs);

       if (err) {

           err = lfs_format(&lfs, &cfg_littlefs);

           err = lfs_mount(&lfs, &cfg_littlefs);

       }

`

even if I take the configuration of the example on the littlefs github page nothing changes.
Thanks for your help,
Mike

**Comment by e107steved** [comment]
It's pretty certain that the problem lies somewhere in your flash routines - so many people are using littleFS that any problems are going to be very obscure.
Some flash operations (erase, write) take some time to complete. Do your flash routines ensure that an operation is complete before starting the next one?
