### ISSUE TITLE
Why does LittleFS sometimes write without validation

### ISSUE THREAD

**Issue by evpopov** [littlefs-project/littlefs#775]
I ran across 3 places in the code where data is programmed to flash, but is not verified. 
I'm quite new to this code base, so I'd appreciate if someone sheds some light on these 3 cases and lets me know if this is by design or if I've uncovered an few "happy accidents"

- lfs_dir_commitprog() calls lfs_bd_prog() with validate=false, causing lfs_bd_flush() to not validate.
- lfs_dir_commitcrc() calls lfs_bd_prog() with validate=false, causing lfs_bd_flush() to not validate.
- lfs_dir_commitcrc() calls lfs_bd_sync() with validate=false, causing lfs_bd_flush() to not validate.

The returns from both lfs_dir_commitcrc() and lfs_dir_commitprog() could cause relocation or compactions up the call stack so it sounds like validate should be true.
Or are the above 3 cases not validating just to preserve the cache? 

Any thoughts, corrections, or clarifications would be greatly appreciated. Thanks!

**Comment by geky** [comment]
Hi @evpopov, thanks for creating an issue. It sure does look funny to have validate=false here.

But note that these are all `lfs_dir_commit*` functions.

Commits in littlefs are validated by a 32-bit CRC. This is normally checked during metadata fetch when reading, but we can also use the CRC here to validate writes without needing to keep the intermediary data in RAM:

https://github.com/littlefs-project/littlefs/blob/6a53d76e90af33f0656333c1db09bd337fa75d23/lfs.c#L1555-L1590

I suppose littlefs could validate every prog call with the buffered data, and not do the CRC check during `lfs_dir_commit`, but doing the CRC check has a higher chance of catching porting errors related to sequential progs. It also helps catch CRC calculation issues.
