### ISSUE TITLE
Using lfs_dir_tell at the end of a directory succeds, but then lfs_dir_seek fails

### ISSUE THREAD

**Issue by sosthene-nitrokey** [littlefs-project/littlefs#785]
Behaviour
========

When iterating over a directory with `lfs_dir_open` and `lfs_dir_read` in a loop, if after calling `lfs_dir_read` on the last file, one calls `lfs_dir_tell`, the call success. However, calling `lfs_dir_seek` with the given value fails with `-22` (invalid).

Expected behaviour
===============

I'd expect this to succeed and only further calls to `lfs_dir_read` to fail. It would also be reasonable to have `lfs_dir_tell` fail too with a `NOENT` error..

Reproducer
=========

The `test_dirs` doesn't iterate over all the files created in the directory, so this bug doesn't happen in the test suite. See #786  for an updated test suite that triggers the bug.

**Comment by geky** [comment]
Hi @sosthene-nitrokey, thanks for creating an issue. I agree with your evaluation.

Out of curiosity I tested telldir/seekdir locally on Linux and it returns a NULL dirent without error. It makes sense as this matches the behavior of file tell/seek when at the end of a file.

I created https://github.com/littlefs-project/littlefs/pull/805 to fix this, let me know if you see any issues with it.
