### ISSUE TITLE
No data upload button?

### ISSUE THREAD

**Issue by Zhek1ch** [littlefs-project/littlefs#792]
I tried to install littlefs to arduino ide 2.0.5 through the plugin, and the library, but the button "ESP32 Sketch data upload"doesn't appear. This is my path for the executable: /Users/zhekich/Documents/Arduino/tools/ESP32FS/tool/esp32fs.jar. I obviously restarted arduino ide, but I still dont understand what the problem is.

**Comment by geky** [comment]
Will do 👍
