### ISSUE TITLE
All blocks get BAD BLOCKS ERROR

### ISSUE THREAD

**Issue by Aravind0812** [littlefs-project/littlefs#808]
Hello,
I am currently working on implementing LittleFS on the W25Q128JV through QSPI.
I am writing data to this file less than cache size I am able to close the file successfully.my data size equal to or above cache size it return -84 (bad block ) (corrupted).After  i get LFS_ERR_NOSPC = -28, // No space left on device
my configuration is 

        // block device operations
     .read  = blockDeviceRead,
    .prog  = blockDeviceProg,
    .erase = blockDeviceErase,
    .sync  = blockDeviceSync,

    /* Block device configuration */
 .read_size = 64,
.prog_size = 64,
.block_size = 4096,
.block_count = 4096,
.cache_size = 64,
 .lookahead_size = 32,
.block_cycles = 500

 int err = lfs_mount(&lfs, &cfg);
         // reformat if we can't mount the filesystem
        // this should only happen on the first boot
        if (err)
       {
                err =  lfs_format(&lfs, &cfg);
        	if(err)
        	{
        		printf("format error : %d\r\n",err);
        		return -1;
        	}
        	err =  lfs_mount(&lfs, &cfg);
        }
        if(err)
        {
             printf("mount error : %d\r\n",err);
             return -1;
        }
        while(1)
        {

            err = lfs_file_open(&lfs, &file, "AILABS",LFS_O_WRONLY | LFS_O_CREAT);
            if(err)
            {
            	printf("file open error : %d\r\n",err);
            	return -1;
            }
           err = lfs_file_seek(&lfs, &file, 0,LFS_SEEK_END);
            if(err < 0)
            {
            	printf("file seek error : %d\r\n",err);
            	return -1;
            }
            printf("file seek :%d\r\n",err);
        	float data[15]={55.23,98.45,876.12,345.8897,555.555,12.96,97.01,67.345,1.1,2.2,1.1,2.2,3.3,4.4,5.5};
            for(int i=0;i<15;i++)
            {
                   err = lfs_file_write(&lfs, &file, &data[i], sizeof(data[i]));
                   if(err <= 0)
                   {
                   		printf("write error :%d\r\n",err);
                   		return -1;
                   	}
                   		printf("Write success %.02f %d\r\n",data[i],err);
            }
           	err = lfs_file_tell(&lfs, &file);
           	if(err <= 0)
           	{
         			printf("file postion error :%d\r\n",err);
           			return -1;
           	}
           	printf("file tell : %d\r\n",err);
          
           	err= lfs_file_close(&lfs, &file);
           	if(err)
           	{
           		  printf("file close error : %d\r\n",err);
           		  return -1;
           	}
        }
      1st time i write the 60 bytes of data is successfully write and closed successfully.
     again i open the file and write the data means it write only one 4 byte data after it give error like this.
    how to slove this issue, my configuration is wrong means please tell me ,it fill only cache size what i provide that that much data only is taking.after i get error.

output:

Write success 55.23  4
Write success 98.45  4
Write success 876.12 4
Write success 345.89 4
Write success 555.55 4
Write success 12.96 4
Write success 97.01 4
Write success 67.35 4
Write success 1.10 4
Write success 2.20 4
Write success 1.10 4
Write success 2.20 4
Write success 3.30 4
Write success 4.40 4
Write success 5.50 4
file tell : 60
prog block : 1 addr : 1152
BUSY...
No longer BUSY...
Operation result: 0
prog block : 1 addr : 1216
BUSY...
No longer BUSY...
Operation result: 0
file seek :60
Write success 55.23 4
erase block: 2501
prog block : 2501 addr : 2561024
BUSY...
No longer BUSY...
Operation result: -84
../Core/Src/lfs.c:3088:debug: Bad block at 0x9c5
                                                erase block: 2502
prog block : 2502 addr : 2562048
BUSY...
No longer BUSY...
Operation result: -84
../Core/Src/lfs.c:3088:debug: Bad block at 0x9c6
.............

how to handle this issue tell me.

**Comment by smitpatel30** [comment]
I think you should add some delay after each iteration. As from your code, it is in infinite while loop . So, there might be manipulation for creating,writing and reading at the same time. Put some delay..
