### ISSUE TITLE
using uninitialized struct

### ISSUE THREAD

**Issue by mdahamshi** [littlefs-project/littlefs#854]
Hey
in `lfs.c` line 880:
`struct lfs_diskoff disk;`

we use disk at line 918 without initializing it, this case an runtime check error in some compilers.
we should initlize it:
`struct lfs_diskoff disk; = {0};`

**Comment by geky** [comment]
Should be resolved by https://github.com/littlefs-project/littlefs/pull/855, thanks for the PR! Will merge on the next path release.

**Comment by mdahamshi** [comment]
Thank you.
