### ISSUE TITLE
ISR_HARDFAULT() error in Raspberry Pi Pico W !!! 

### ISSUE THREAD

**Issue by JITU-SYS** [littlefs-project/littlefs#991]
Hello @earlephilhower,
I am using arduino ide 2.0 and my controller is Raspberry Pi Pico W . My code is compiling successfully and it is working just fine for some days . But sometimes while initializing Quicktel EG25 GSM Modem , it gets stuck and after that it is unable to recover from that until I manually reset the board . I have checked and there are no power issues related to GSM module .

Therefore to solve that issue , I used Raspberry Pi debug probe and following are the logs from the debug console .

![img_20240607(2)](https://github.com/littlefs-project/littlefs/assets/172017636/74376b54-c91d-46be-b886-f0d5a4d0caa7)
![img_20240607(1)](https://github.com/littlefs-project/littlefs/assets/172017636/682cd743-2396-48be-ac09-3086ca6e0e51)
![img_20240607](https://github.com/littlefs-project/littlefs/assets/172017636/e7adabb6-7ec9-4b45-9e9f-a2848fd17d93)

LittleFS is the file system I am using .

Please guide me immediately to solve this issue .

**Comment by geky** [comment]
You will probably get better help if you open this on an actual Pico repo (https://github.com/earlephilhower/arduino-pico, I think?).

This repo is focused on LittleFS's core, which is a step removed from actual hardware.

**Comment by earlephilhower** [comment]
I think you can close this, @geky .  The original author posted this here, in the arduino-pico repo, and on the Arduino.cc forums and disappeared.  There was no indication of any issue w/LittleFS or the core, and no MCVE was ever produced.  The pictures of text output from GDB above have nothing point to either, just the usual output when you connect after-the-fact through OpenOCD and GDB.

LittleFS has been absolutely awesome for the RPi Pico and ESP8266 Arduino cores.  Thanks to all the contributors!

**Comment by geky** [comment]
This is not the first or last unrelated issue opened here, so no worries. Best of luck in arduino-pico-land.
